<?php
declare(strict_types=1);

use Blackbird\HyvaSplideJs\Api\HyvaSplideJSInterface;
use Blackbird\HyvaSplideJs\Api\RequirementsInterface;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
?>
<script>
    (() => {
        function loadJSLibrary() {
            return new Promise(resolve => {
                const script = document.createElement('script');
                script.type = 'text/javascript';
                script.src = '<?= $escaper->escapeUrl(
                    $block->getViewFileUrl(RequirementsInterface::URL_SPLIDE_MIN_JS)
                ) ?>';
                script.async = true;
                script.onload = resolve;
                document.head.appendChild(script);
            })
        }
        function loadCssLibrary() {
            return new Promise(resolve => {
                const link = document.createElement('link');
                link.rel = "stylesheet";
                link.type = "text/css";
                link.href = '<?= $escaper->escapeUrl(
                    $block->getViewFileUrl(RequirementsInterface::URL_SPLIDE_MIN_CSS)
                ) ?>';
                link.onload = resolve;
                document.head.appendChild(link);
            })
        }

        function loadScripts() {
            if(isScriptAdded()){
                return;
            }

            Promise.all([loadJSLibrary(), loadCssLibrary()]).then(() => updateStoreState());
        }
        function updateStoreState() {
            Alpine.store('<?= HyvaSplideJSInterface::HYVA_SPLIDE_JS ?>').is_loaded = true;
        }
        function isScriptAdded() {
            const scripts = document.scripts;
            const scriptsContainingSplide = Array.from(scripts).filter((script) => {
                if(!script.src){
                    return false;
                }

                return script.src.includes(
                    '<?= RequirementsInterface::FILE_NAME_SPLIDE_MIN_JS ?>'
                );
            })

            return scriptsContainingSplide.length;
        }

        function initializeStoreState() {
            Alpine.store('<?= HyvaSplideJSInterface::HYVA_SPLIDE_JS ?>', {
                is_loaded: false,

                forceLoad() {
                    loadScripts();
                }
            });
        }

        document.addEventListener("alpine:init", () => {
            initializeStoreState();

            if (!document.getElementsByClassName('splide').length) {
                return;
            }

            loadScripts();
        });
    })();
</script>
