<?php
declare(strict_types=1);

use Blackbird\HyvaSplideJS\Api\HyvaSplideJSInterface;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
?>
<script>
    (() => {
        function loadJSLibrary() {
            return new Promise(resolve => {
                const script = document.createElement('script');
                script.type = 'text/javascript';
                script.src = '<?= $escaper->escapeUrl(
                    $block->getViewFileUrl(HyvaSplideJSInterface::URL_SPLIDE_MIN_JS)
                ) ?>';
                script.async = true;
                script.onload = resolve;
                document.head.appendChild(script);
            })
        }
        function loadCssLibrary() {
            return new Promise(resolve => {
                const link = document.createElement('link');
                link.rel = "stylesheet";
                link.type = "text/css";
                link.href = '<?= $escaper->escapeUrl(
                    $block->getViewFileUrl(HyvaSplideJSInterface::URL_SPLIDE_MIN_CSS)
                ) ?>';
                link.onload = resolve;
                document.head.appendChild(link);
            })
        }

        function loadScripts() {
            if(isScriptAdded()){
                return;
            }

            Promise.all([loadJSLibrary(), loadCssLibrary()]).then(() => dispatchEvent());
        }
        function dispatchEvent() {
            window.dispatchEvent(
                new CustomEvent('<?= $escaper->escapeJs(HyvaSplideJSInterface::EVENT_SPLIDE_LOADED) ?>')
            );
        }
        function isScriptAdded() {
            const scripts = document.scripts;
            for(const script in scripts) {
                if(!scripts[script].src){
                    continue;
                }

                if(scripts[script].src.includes(
                    '<?= $escaper->escapeUrl(HyvaSplideJSInterface::URL_SPLIDE_MIN_JS) ?>'
                )){
                    return true;
                }
            }
            return false;
        }

        document.addEventListener("alpine:init", () => {
            if (!document.getElementsByClassName('splide').length) {
                return;
            }

            loadScripts();
        });
    })();
</script>
